version: '3'
services:
  repo:
    image: re-zero-tdd
    build:
      context: ./ops/repo
    volumes:
      - .:/repo
    working_dir: "/repo"
  env-python:
    image: env-python
    build:
      context: ./ops/env/python
    ports:
      - 5901:5901
      - 6901:6901
    volumes:
      - ./dev:/headless/Desktop/dev
    environment:
      - VNC_PW=guest
