version: 2
jobs:
  build:
    docker:
    - image: hiroshimaarc/re-zero-tdd:1.1.0
    working_directory: ~/repo
    steps:
    - checkout
    - run:
        name: Running all tests
        command: rake test:all

